# Generated by Django 6.0 on 2025-12-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galaxies', '0001_initial'),
        ('sources', '0001_initial'),
        ('subtypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.source')),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subtypes.subtype')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_types', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'sub_type', 'source')},
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('lumdist', 'Luminosity distance'), ('velocity', 'Recessional velocity'), ('redshift', 'Redshift'), ('maxabsmag', 'Max absolute magnitude'), ('maxappmag', 'Max apparent magnitude')], max_length=32)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=32)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.source')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'name'], name='events_attr_event_i_bc62c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='HostGalaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_galaxies', to='events.event')),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='galaxies.galaxy')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.source')),
            ],
            options={
                'unique_together': {('event', 'galaxy', 'source')},
            },
        ),
    ]
