# Generated by Django 6.0 on 2025-12-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='name',
            field=models.CharField(db_index=True, max_length=126),
        ),
    ]
