# Generated by Django 6.0 on 2025-12-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('hostra', models.TimeField(blank=True, null=True)),
                ('hostdec', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
