# Generated by Django 6.0 on 2025-12-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxy',
            name='hostdec',
        ),
        migrations.RemoveField(
            model_name='galaxy',
            name='hostra',
        ),
    ]
