# Generated by Django 6.0 on 2025-12-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxies', '0002_remove_galaxy_hostdec_remove_galaxy_hostra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxy',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
