# Generated by Django 6.0 on 2025-12-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('bibcode', models.CharField(blank=True, max_length=19, null=True)),
                ('doi', models.CharField(blank=True, max_length=256, null=True)),
                ('secondary', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
