# Generated by Django 6.0 on 2025-12-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['name'], name='sources_sou_name_d7c3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['url'], name='sources_sou_url_ff9a06_idx'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(('bibcode__isnull', False)), fields=('bibcode',), name='unique_bibcode_when_not_null'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(condition=models.Q(('doi__isnull', False)), fields=('doi',), name='unique_doi_when_not_null'),
        ),
    ]
